import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"

import logo from "../assets/logo.png"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Snap A Day</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="min-h-[80vh] flex flex-row justify-evenly gap-4 items-center">
          <div className="flex flex-col justify-center gap-4 items-start ">
            <h1 className="text-6xl text-red-400">Snap a day</h1>
            <p className="text-3xl">Track your Memories</p>
            <div className="flex flex-row gap-4">
              <button className="btn rounded">
                <a href="/app">Start Now</a>
              </button>
              <button className="btn rounded">
                <a href="/app/login">Login</a>
              </button>
            </div>
          </div>
          <div className="w-96 h-96">
            <Image src={logo} width={800} height={800} />
          </div>
        </section>

        {/* <section className="min-h-[75vh] flex flex-col justify-center items-center">
          <h2 className="text-4xl">Yo! Lots of people use this bruh!</h2>
        </section>

        <section className="min-h-[75vh] flex flex-col justify-center items-center">
          <p>Footer stuff</p>
          <p className="justify-self-end">Don't copy our stuff mate © 2023</p>
        </section> */}
      </main>
    </>
  )
}
