import Head from "next/head"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

const images = [
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
  {
    image: "This will eventually be an image",
  },
]

const snaps = [
  {
    snap: "This will eventually be a snap",
  },
  {
    snap: "This will eventually be a snap",
  },
  {
    snap: "This will eventually be a snap",
  },
  {
    snap: "This will eventually be a snap",
  },
  {
    snap: "This will eventually be a snap",
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Snap A Day</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto min-h-screen flex flex-col items-center">
        <h1 className="text-4xl text-red-400">Explorer</h1>

        <div className="w-full flex flex-row justify-start items-center gap-2">
          {snaps.map((snap) => {
            return <div className="w-40 h-72">{snap.snap}</div>
          })}
        </div>

        <div className="w-full p-4 flex flex-row justify-start items-center gap-2 flex-wrap">
          {images.map((image) => {
            return <div className="w-40 h-40">{image.image}</div>
          })}
        </div>

        <button className="fixed bottom-32 right-40">Plus</button>
      </main>
    </>
  )
}
